#!/usr/bin/env bash
#
# run-refresh-remote — portable remote wrapper around refresh-free-models.mjs.
#
# The bare script only rewrites a local checkout of lib/openrouter.ts, which is
# useless on an ephemeral cloud worker. This wrapper makes the refresh durable:
# it clones the repo, runs the refresh, and — only if the chain actually
# changed — pushes a branch and opens/updates a PR. Idempotent by design:
# no change => no commit, no PR, clean exit 0.
#
# Runs unchanged on GCP Cloud Run, Modal, or a Zo automation. Needs only bash,
# git, gh (or a plain git push), and Node 18+.
#
# Required env:
#   OPENROUTER_API_KEY   passed to the probe
#   GH_TOKEN             GitHub PAT (repo scope) for clone + push + PR
# Optional env:
#   REPO                 default: adamaslan/nuwrrrld-portal
#   BASE_BRANCH          default: main
#   PR_BRANCH            default: chore/refresh-free-models
#   MODEL_CHAIN_SIZE     forwarded to the refresh script (default 4)
#   OPEN_PR              "1" (default) opens/updates a PR; "0" pushes to BASE_BRANCH directly
#
# Exit codes: 0 = success (changed or not), 1 = refresh unsafe / hard error.
set -euo pipefail

REPO="${REPO:-adamaslan/nuwrrrld-portal}"
BASE_BRANCH="${BASE_BRANCH:-main}"
PR_BRANCH="${PR_BRANCH:-chore/refresh-free-models}"
OPEN_PR="${OPEN_PR:-1}"

: "${OPENROUTER_API_KEY:?OPENROUTER_API_KEY is required}"
: "${GH_TOKEN:?GH_TOKEN (GitHub PAT, repo scope) is required}"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

echo "==> Cloning $REPO@$BASE_BRANCH"
git clone --depth 1 --branch "$BASE_BRANCH" \
  "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" "$workdir/repo"
cd "$workdir/repo"

git config user.name  "free-model-bot"
git config user.email "free-model-bot@users.noreply.github.com"

echo "==> Refreshing FREE_MODEL_CHAIN"
# The refresh script exits 1 on an unsafe result and leaves the file untouched;
# `set -e` propagates that so the job is marked failed without pushing garbage.
node scripts/refresh-free-models.mjs

if git diff --quiet -- lib/openrouter.ts; then
  echo "==> No change — chain already current. Nothing to push."
  exit 0
fi

echo "==> Chain changed:"
git --no-pager diff -- lib/openrouter.ts

commit_msg="chore: refresh FREE_MODEL_CHAIN (automated)

Regenerated by refresh-free-models.mjs — probed OpenRouter's live \$0/:free
catalog and kept the reachable models in preference order.
"

if [[ "$OPEN_PR" == "0" ]]; then
  echo "==> Pushing directly to $BASE_BRANCH"
  git commit -am "$commit_msg"
  git push origin "HEAD:${BASE_BRANCH}"
  exit 0
fi

echo "==> Opening/updating PR on branch $PR_BRANCH"
git checkout -B "$PR_BRANCH"
git commit -am "$commit_msg"
git push -f origin "$PR_BRANCH"

if command -v gh >/dev/null 2>&1; then
  # `gh pr view` returns exit 0 even for a closed/merged PR on this branch,
  # which would wrongly skip `gh pr create` on the next run after a merge.
  # Only an *open* PR should be treated as "already exists".
  open_pr="$(gh pr list --repo "$REPO" --head "$PR_BRANCH" --state open --json number --jq '.[0].number // empty' 2>/dev/null || true)"
  if [[ -n "$open_pr" ]] && [[ "$open_pr" != "null" ]]; then
    echo "==> PR #$open_pr already open for $PR_BRANCH — force-push updated it."
  else
    gh pr create --repo "$REPO" \
      --base "$BASE_BRANCH" --head "$PR_BRANCH" \
      --title "chore: refresh FREE_MODEL_CHAIN (automated)" \
      --body "Automated weekly refresh of the free-tier model fallback chain. See scripts/refresh-free-models.mjs."
  fi
else
  echo "==> gh not available; branch $PR_BRANCH pushed. Open the PR manually or set OPEN_PR=0."
fi
