import Link from "next/link";
import type { Metadata } from "next";
import "../legal.css";

export const metadata: Metadata = {
  title: "Terms of Service · NuWrrrld Financial",
  description: "The terms governing your use of NuWrrrld Financial.",
};

const LAST_UPDATED = "2026-06-28";

export default function TermsOfService() {
  return (
    <div className="nwf-legal">
      <div className="legal-topbar">
        <Link className="brand" href="/">
          <span className="brand-mark" aria-hidden="true">NWF</span>
          <span>NuWrrrld Financial</span>
        </Link>
        <Link className="legal-back" href="/">← Back</Link>
      </div>

      <main className="legal-wrap">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: {LAST_UPDATED}</p>

        <h2>1. Overview</h2>
        <p>
          These Terms of Service ("Terms") govern your access to and use of NuWrrrld
          Financial's website, mobile application, and services (collectively, the
          "Service"). By accessing or using the Service, you agree to be bound by
          these Terms. If you do not agree to these Terms, you may not use the Service.
        </p>

        <h2>2. Not financial or investment advice</h2>
        <p>
          <strong>NuWrrrld Financial does not provide personalized financial,
          investment, legal, or tax advice.</strong> Our Service provides informational
          tools, market briefings, signals, trade analysis (Hold/Fold verdicts), and
          AI-generated commentary (the "AI Council"). These are educational tools and
          information products only.
        </p>
        <p>
          No fiduciary or advisory relationship is created by your use of the Service.
          You are solely responsible for your own investment decisions and should
          consult with a licensed financial advisor, tax professional, or attorney
          before taking any action based on information from our Service. Past
          performance is not indicative of future results.
        </p>

        <h2>3. AI-generated content disclaimer</h2>
        <p>
          The AI Council, signals, and other AI-generated output are generated by
          machine learning models and may be:
        </p>
        <ul>
          <li>Inaccurate, incomplete, or out of date</li>
          <li>Based on incomplete or biased training data</li>
          <li>Probabilistic estimates, not statements of fact</li>
        </ul>
        <p>
          You agree not to rely solely on AI output for any financial or investment
          decision. Always perform your own due diligence and consult qualified professionals.
        </p>

        <h2>4. Account and eligibility</h2>
        <p>
          You represent that you are at least 18 years of age and have the legal
          capacity to enter into these Terms. You agree to provide accurate, current,
          and complete information during sign-up and to keep your account information
          up to date. You are responsible for maintaining the confidentiality of your
          credentials and for all activity under your account.
        </p>

        <h2>5. Acceptable use</h2>
        <p>
          You agree not to:
        </p>
        <ul>
          <li>Violate applicable laws or regulations</li>
          <li>Attempt to gain unauthorized access to the Service or its systems</li>
          <li>Interfere with or disrupt the Service or its infrastructure</li>
          <li>Copy, scrape, or extract data from the Service except as expressly permitted</li>
          <li>Use the Service to manipulate markets, engage in fraud, or create misleading information</li>
          <li>Harass, defame, or otherwise violate the rights of others</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate your account if you violate these
          Terms or applicable law.
        </p>

        <h2>6. Subscriptions and billing</h2>
        <p>
          Some features of the Service require payment. Billing is handled by Stripe, our
          third-party payment processor. By initiating a subscription, you authorize us to
          charge your payment method on a recurring basis according to your chosen plan.
          Subscriptions renew automatically unless cancelled. You may cancel at any time
          through your account settings, and cancellation takes effect at the end of your
          current billing cycle.
        </p>
        <p>
          All prices are subject to change with 30 days notice. We are not responsible for
          any fees or charges imposed by your payment provider.
        </p>

        <h2>7. No warranty; limitation of liability</h2>
        <p>
          <strong>The Service is provided "as is" and "as available" without warranties
          of any kind, express or implied, including merchantability, fitness for a
          particular purpose, or non-infringement.</strong>
        </p>
        <p>
          To the maximum extent permitted by law, NuWrrrld Financial shall not be liable
          for any indirect, incidental, special, consequential, or punitive damages,
          including trading losses, lost profits, or business interruption, arising from
          your use of the Service, even if we have been advised of the possibility of such
          damages.
        </p>

        <h2>8. Intellectual property</h2>
        <p>
          All content, features, and functionality of the Service (including text, graphics,
          algorithms, and code) are owned by NuWrrrld Financial or its licensors and are
          protected by copyright, trademark, and other intellectual property laws. You may
          not reproduce, distribute, or transmit content without our written permission.
        </p>

        <h2>9. Third-party links and services</h2>
        <p>
          The Service may contain links to third-party websites and services. We do not
          endorse and are not responsible for the content, accuracy, policies, or practices
          of third-party sites. Your use of third-party services is governed by their terms
          and policies.
        </p>

        <h2>10. Privacy</h2>
        <p>
          Your use of the Service is also governed by our{" "}
          <Link className="inline" href="/privacy-policy">Privacy Policy</Link>
          , which describes how we collect and use your information.
        </p>

        <h2>11. Changes to these terms</h2>
        <p>
          We may update these Terms at any time. Material changes will be noted by updating
          the "Last updated" date above. Your continued use of the Service after changes
          constitutes your acceptance of the updated Terms. If you do not agree to any
          changes, you must discontinue use of the Service.
        </p>

        <h2>12. Governing law and dispute resolution</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws of the
          State of California, without regard to its conflict of law principles. Any
          dispute arising under these Terms shall be subject to the exclusive jurisdiction
          of the courts located in San Francisco County, California.
        </p>

        <h2>13. Termination</h2>
        <p>
          We may terminate or suspend your account and access to the Service at any time,
          with or without cause, and without notice. Upon termination, your right to use
          the Service immediately ceases.
        </p>

        <h2>14. Contact</h2>
        <p>
          For questions about these Terms or to report a violation:{" "}
          <a className="inline" href="mailto:chillcoders@gmail.com">
            chillcoders@gmail.com
          </a>.
        </p>

        <p className="legal-footer">
          © {new Date().getFullYear()} NuWrrrld Financial. All rights reserved.
        </p>
      </main>
    </div>
  );
}
